/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/cvrkec.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cvrkec.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['6Noha'].geometry} material={nodes['6Noha'].material} position={[0.9, -0.5, 0]} scale={[0.055, 0.5, 0.055]} />
      <mesh geometry={nodes['1Noha14'].geometry} material={nodes['1Noha14'].material} position={[0.9, -0.5, -0.9]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['1Noha24'].geometry} material={nodes['1Noha24'].material} position={[-0.9, -0.5, -0.9]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['1Noha34'].geometry} material={nodes['1Noha34'].material} position={[-0.9, -0.5, 0.9]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['1Noha44'].geometry} material={nodes['1Noha44'].material} position={[0.9, -0.5, 0.9]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['2Noha14'].geometry} material={nodes['2Noha14'].material} position={[0.9, -0.5, 0]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['2Noha24'].geometry} material={nodes['2Noha24'].material} position={[0, -0.5, -0.9]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['2Noha34'].geometry} material={nodes['2Noha34'].material} position={[-0.9, -0.5, 0]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['2Noha44'].geometry} material={nodes['2Noha44'].material} position={[0, -0.5, 0.9]} scale={[0.05, 0.5, 0.05]} />
      <mesh geometry={nodes['3Noha1'].geometry} material={nodes['3Noha1'].material} scale={[1, 1, 0.173]} />
      <mesh geometry={nodes['4Noha1'].geometry} material={nodes['4Noha1'].material} position={[-0.765, 0, -0.765]} rotation={[0, 1.571, 0]} scale={[-0.101, -1, -0.98]} />
      <mesh geometry={nodes['5oha1001'].geometry} material={nodes['5oha1001'].material} position={[-0.765, 0, -0.765]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.101, -1, -0.98]} />
      <mesh geometry={nodes.Ctverec.geometry} material={materials['texture2.003']} scale={[1, 0.015, 1]} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[3.511, 1.289, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.063, -0.014, -0.101]} />
      <mesh geometry={nodes.hexagon.geometry} material={nodes.hexagon.material} scale={[1.2, 1, 1.2]} />
      <mesh geometry={nodes.hexagon45.geometry} material={nodes.hexagon45.material} scale={[1.2, 1, 1.2]} />
      <mesh geometry={nodes.Kruh.geometry} material={nodes.Kruh.material} scale={[1, 0.015, 1]} />
      <mesh geometry={nodes.Natural.geometry} material={nodes.Natural.material} position={[0, 1.434, 0]} scale={[1, 0.03, 1.6]} />
      <mesh geometry={nodes['7Noha001'].geometry} material={nodes['7Noha001'].material} position={[0.9, -0.5, -0.9]} rotation={[-3.133, -0.02, -2.359]} scale={[0.05, 0.5, 0.05]} />
    </group>
  )
}

useGLTF.preload('/cvrkec.gltf')
